import type { Metadata } from "next";

import Link from "next/link";
import { title } from "process";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{
  children: React.ReactNode;
}>) {
  const fiberList = [
    {
      title: 'Add Canvas',
      link: '/auth-stack/Fiber/Basic'
    },
    {
      title: 'Add Shape',
      link: '/auth-stack/Fiber/Add-Mesh'
    },
    {
      title: 'Move and Scale Mesh',
      link: '/auth-stack/Fiber/Move-Mesh'
    },
    {
      title: 'Group and Rotation',
      link: '/auth-stack/Fiber/Group-and-Rotation'
    },
    {
      title: 'Use Freame Hook',
      link: '/auth-stack/Fiber/Use-Frame-Hook'
    },
    {
      title: 'Camera',
      link: '/auth-stack/Fiber/Camera'
    },
    {
      title: 'Canvas Props',
      link: '/auth-stack/Fiber/Orthographic-Camera'
    },
    {
      title: 'Axes Helper',
      link: '/auth-stack/Fiber/Axes-Helper'
    },
    {
      title: 'Grid Helper',
      link: '/auth-stack/Fiber/Grid-Helper'
    },
    {
      title: 'Texture Loader',
      link: '/auth-stack/Fiber/Texture-Loader'
    },
    {
      title: 'GLTF Loader',
      link: '/auth-stack/Fiber/GLTF-Loader'
    },
  ];




  const dreiList1 = [
    {
      title: 'Shapes',
      link: '/auth-stack/Drei/Shapes'
    },
  ];

  const dreiList2 = [
    {
      title: 'useGLTF',
      link: '/auth-stack/Drei/Loaders/Use-GLTF'
    },
    {
      title: 'useTexture',
      link: '/auth-stack/Drei/Loaders/Use-Texture'
    },
    {
      title: 'useCubeTexture',
      link: '/auth-stack/Drei/Loaders/Use-Cube-Texture'
    },
    {
      title: 'useSVG',
      link: '/auth-stack/Drei/Loaders/Use-SVG'
    },
    {
      title: 'useVideoTexture',
      link: '/auth-stack/Drei/Loaders/Use-Video-Texture'
    },

  ];

  const dreiList3 = [
    {
      title: 'Billboard',
      link: '/auth-stack/Drei/Abstaction/Billboard'
    },
    {
      title: 'Detailed',
      link: '/auth-stack/Drei/Abstaction/Detailed'
    },
    {
      title: 'Image',
      link: '/auth-stack/Drei/Abstaction/Image'
    },
    {
      title: 'Svg',
      link: '/auth-stack/Drei/Abstaction/Svg'
    },
    {
      title: 'Outlines',
      link: '/auth-stack/Drei/Abstaction/Outlines'
    },
    {
      title: 'Positional Audio',
      link: '/auth-stack/Drei/Abstaction/PositionalAudio'
    },
    {
      title: '3D Text',
      link: '/auth-stack/Drei/Abstaction/3DText'
    },
  ];

  const dreiList4 = [
    {
      title: 'Curve Modifier',
      link: '/auth-stack/Drei/Modifier/CurveModifier'
    },
  ];
  const dreiList5 = [
    {
      title: 'Orbital Controls',
      link: '/auth-stack/Drei/Controls/OrbitControls'
    },
    {
      title: 'Keyboard Controls',
      link: '/auth-stack/Drei/Controls/KeyboardControls'
    },
    {
      title: 'Camera Controls',
      link: '/auth-stack/Drei/Controls/CameraControls'
    },
    {
      title: 'Presentation Controls',
      link: '/auth-stack/Drei/Controls/PresentationControls'
    },
    {
      title: 'Scroll Controls',
      link: '/auth-stack/Drei/Controls/ScrollControls'
    },
  ];
  return (
    <html lang="en">
      <body >
        <div className="bg-white w-full h-[100vh] relative overflow-hidden">
          <nav className="relative inline-block w-[200px] h-[100%] bg-red-400 px-3 overflow-auto">
            <div className="w-full text-center text-2xl font-bold text-white mt-3">
              Magical Component
            </div>
            <div className="w-full my-3 flex justify-center">
              <div className="under-line h-[5px] bg-white w-full"></div>
            </div>

            <strong className="text-[25px]">Fiber</strong>
            {fiberList.map((item, index) => (
              <Link href={item.link} key={index}>
                <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                  {item?.title || ''}
                </div>
              </Link>
            ))}
            <strong className="text-[25px] mt-4 block">Drei</strong>
            <strong className="text-[16px] mt-2 block">1.Shapes</strong>

            {dreiList1.map((item, index) => (
              <Link href={item.link} key={index}>
                <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                  {item?.title || ''}
                </div>
              </Link>
            ))}
            <strong className="text-[16px] mt-2 block">2.Loaders</strong>
            {dreiList2.map((item, index) => (
              <Link href={item.link} key={index}>
                <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                  {item?.title || ''}
                </div>
              </Link>
            ))}
            <strong className="text-[16px] mt-2 block">3.Abstactions</strong>
            {dreiList3.map((item, index) => (
              <Link href={item.link} key={index}>
                <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                  {item?.title || ''}
                </div>
              </Link>
            ))}
            <strong className="text-[16px] mt-2 block">4.Modifier</strong>
            {dreiList4.map((item, index) => (
              <Link href={item.link} key={index}>
                <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                  {item?.title || ''}
                </div>
              </Link>
            ))}
            <strong className="text-[16px] mt-2 block">5.Controls</strong>
            {dreiList5.map((item, index) => (
              <Link href={item.link} key={index}>
                <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                  {item?.title || ''}
                </div>
              </Link>
            ))}
          </nav>
          <main className="absolute inline-block h-[100%]  overflow-hidden" style={{ width: 'calc(100% - 200px)' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
