import type { Metadata } from "next";

import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{
children: React.ReactNode;}>) {
  const navList = [
    {
      title: 'Fiber',
      link: '/auth-stack/Fiber'
    },
    {
      title: 'Drei',
      link: '/auth-stack/Drei'
    },
    {
      title: 'Rapier',
      link: '/auth-stack/Rapier'
    },
  ];
  const fiberList=[
    {
      title: 'Add Canvas',
      link: '/auth-stack/Fiber/Basic'
    },
    {
      title: 'Add Shape',
      link: '/auth-stack/Fiber/Add-Mesh'
    },
    {
      title: 'Move and Scale Mesh',
      link: '/auth-stack/Fiber/Move-Mesh'
    },
    {
      title: 'Group and Rotation',
      link: '/auth-stack/Fiber/Group-and-Rotation'
    },
    {
      title: 'Use Freame Hook',
      link: '/auth-stack/Fiber/Use-Frame-Hook'
    },
    {
      title: 'Camera',
      link: '/auth-stack/Fiber/Camera'
    },
    {
      title: 'Canvas Props',
      link: '/auth-stack/Fiber/Orthographic-Camera'
    },
    {
      title: 'Axes Helper',
      link: '/auth-stack/Fiber/Axes-Helper'
    },
    {
      title: 'Grid Helper',
      link: '/auth-stack/Fiber/Grid-Helper'
    },
    {
      title: 'Texture Loader',
      link: '/auth-stack/Fiber/Texture-Loader'
    },
    {
      title: 'GLTF Loader',
      link: '/auth-stack/Fiber/GLTF-Loader'
    },
  ];
  
  const dreiList=[
    {
      title: 'UseGLTF',
      link: '/auth-stack/Drei/Use-GLTF'
    },
  ];
  return (
    <html lang="en">
      <body >
        <div className="bg-white w-full h-[100vh] relative overflow-hidden">
          <nav className="relative inline-block w-[200px] h-[100%] bg-red-400 px-3 overflow-auto">
            <div className="w-full text-center text-2xl font-bold text-white mt-3">
              Magical Component
            </div>
            <div className="w-full my-3 flex justify-center">
              <div className="under-line h-[5px] bg-white w-full"></div>
            </div>

            <strong className="text-[25px]">Fiber</strong>
            {fiberList.map((item, index) => (
              <Link href={item.link} key={index}>
              <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                {item?.title || ''}
              </div>
              </Link>
            ))}
            <strong className="text-[25px]">Drei</strong>
            {dreiList.map((item, index) => (
              <Link href={item.link} key={index}>
              <div key={index} className="p-[10px_0px] w-full mb-3 bg-red-200 flex justify-center items-center cursor-pointer" style={{ borderRadius: '10px' }}>
                {item?.title || ''}
              </div>
              </Link>
            ))}
          </nav>
          <main className="absolute inline-block h-[100%]  overflow-hidden" style={{ width: 'calc(100% - 200px)' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
