import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navList=[
    {
      title:'Option 1',
      link:''
    },
    {
      title:'Option 2',
      link:''
    },
    {
      title:'Option 3',
      link:''
    },
    {
      title:'Option 4',
      link:''
    }
  ];
  return (
    <html lang="en">
      <body>
        <div className="bg-slate-400 w-full h-[100vh] relative overflow-hidden">
           <main className="w-full h-full">{children}</main> 
        </div>
      </body>
    </html>
  );
}
