import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className="overflow-hidden">
        <div className="bg-slate-400 relative overflow-hidden">
           <main className="w-full h-full">{children}</main> 
        </div>
      </body>
    </html>
  );
}
